// app/coverletter-viewer.tsx
import { useData } from "@/providers/DataProvider";
import { useTheme } from "@/providers/ThemeProvider";
import { Ionicons } from "@expo/vector-icons";
import * as Print from "expo-print";
import { useLocalSearchParams, useRouter } from "expo-router";
import * as Sharing from "expo-sharing";
import React, { useCallback, useState } from "react";
import {
  ActionSheetIOS,
  ActivityIndicator,
  Alert,
  Modal,
  Platform,
  Pressable,
  SafeAreaView,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";

const TONE_LABELS: Record<string, string> = {
  formal: "Formal",
  confident: "Confident",
  bold: "Bold",
};

function buildCoverLetterHtml(cl: any): string {
  const today = new Date().toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/>
    <style>
      * { margin:0; padding:0; box-sizing:border-box; }
      body { font-family:'Georgia',serif; font-size:12px; color:#1a1a1a; padding:60px 72px; line-height:1.7; max-width:680px; margin:0 auto; }
      .date { color:#555; margin-bottom:28px; }
      .to-block { margin-bottom:28px; line-height:1.6; }
      .to-block .name { font-weight:700; font-size:13px; }
      .to-block .company { color:#444; }
      .subject { font-weight:700; font-size:13px; margin-bottom:24px; }
      .greeting { margin-bottom:20px; font-size:13px; }
      .body { font-size:12px; line-height:1.9; color:#222; white-space:pre-wrap; margin-bottom:32px; }
      .signoff { font-size:12px; color:#333; }
      .signoff-name { font-weight:700; margin-top:32px; font-size:13px; }
      .meta { border-top:1px solid #e5e7eb; margin-top:40px; padding-top:16px; color:#888; font-size:10px; font-family:'Helvetica Neue',sans-serif; }
    </style></head><body>
    <div class="date">${today}</div>
    ${
      cl.hiringManager || cl.company
        ? `
      <div class="to-block">
        ${cl.hiringManager ? `<div class="name">${cl.hiringManager}</div>` : ""}
        ${cl.company ? `<div class="company">${cl.company}</div>` : ""}
      </div>`
        : ""
    }
    ${cl.jobTitle ? `<div class="subject">Re: ${cl.jobTitle}</div>` : ""}
    ${
      cl.hiringManager
        ? `<div class="greeting">Dear ${cl.hiringManager},</div>`
        : `<div class="greeting">Dear Hiring Manager,</div>`
    }
    <div class="body">${(cl.body ?? "").replace(/</g, "&lt;").replace(/>/g, "&gt;")}</div>
    <div class="signoff">Sincerely,<div class="signoff-name">&nbsp;</div></div>
    <div class="meta">${cl.title ?? "Cover Letter"} · Generated by Filo</div>
    </body></html>`;
}

function MetaRow({
  icon,
  label,
  value,
  colors,
}: {
  icon: string;
  label: string;
  value: string;
  colors: any;
}) {
  if (!value?.trim()) return null;
  return (
    <View style={styles.metaRow}>
      <Ionicons name={icon as any} size={14} color={colors.textTertiary} />
      <Text style={[styles.metaLabel, { color: colors.textTertiary }]}>
        {label}
      </Text>
      <Text style={[styles.metaValue, { color: colors.text }]}>{value}</Text>
    </View>
  );
}

// ── Android-friendly action sheet ──
function ActionMenu({
  visible,
  onClose,
  onExport,
  onEdit,
  colors,
}: {
  visible: boolean;
  onClose: () => void;
  onExport: () => void;
  onEdit: () => void;
  colors: any;
}) {
  if (!visible) return null;
  return (
    <Modal
      transparent
      animationType="fade"
      visible={visible}
      onRequestClose={onClose}
    >
      <Pressable style={styles.overlay} onPress={onClose}>
        <View
          style={[
            styles.menuCard,
            { backgroundColor: colors.surface, borderColor: colors.border },
          ]}
        >
          <TouchableOpacity
            style={styles.menuItem}
            onPress={() => {
              onClose();
              onExport();
            }}
          >
            <Ionicons name="share-outline" size={18} color={colors.accent} />
            <Text style={[styles.menuItemText, { color: colors.text }]}>
              Export as PDF
            </Text>
          </TouchableOpacity>
          <View
            style={[styles.menuDivider, { backgroundColor: colors.border }]}
          />
          <TouchableOpacity
            style={styles.menuItem}
            onPress={() => {
              onClose();
              onEdit();
            }}
          >
            <Ionicons name="pencil-outline" size={18} color={colors.text} />
            <Text style={[styles.menuItemText, { color: colors.text }]}>
              Edit Cover Letter
            </Text>
          </TouchableOpacity>
        </View>
      </Pressable>
    </Modal>
  );
}

export default function CoverLetterViewerScreen() {
  const { colors } = useTheme();
  const { coverLetters } = useData();
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const cl = coverLetters.find((c) => c.id === id);
  const [exporting, setExporting] = useState(false);
  const [menuVisible, setMenuVisible] = useState(false);

  const handleExportPdf = useCallback(async () => {
    if (!cl) return;
    try {
      setExporting(true);
      const html = buildCoverLetterHtml(cl);
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      const canShare = await Sharing.isAvailableAsync();
      if (!canShare) {
        Alert.alert("Sharing not available", `PDF saved to: ${uri}`);
        return;
      }
      await Sharing.shareAsync(uri, {
        mimeType: "application/pdf",
        dialogTitle: `Share ${cl.title ?? "Cover Letter"}`,
        UTI: "com.adobe.pdf",
      });
    } catch (e: any) {
      Alert.alert("Export failed", e?.message ?? "Could not generate PDF.");
    } finally {
      setExporting(false);
    }
  }, [cl]);

  const handleEdit = useCallback(() => {
    router.push({
      pathname: "/coverletter-editor",
      params: { id: cl?.id },
    } as never);
  }, [cl, router]);

  const handleMorePress = useCallback(() => {
    if (Platform.OS === "ios") {
      ActionSheetIOS.showActionSheetWithOptions(
        {
          options: ["Cancel", "Export as PDF", "Edit Cover Letter"],
          cancelButtonIndex: 0,
        },
        (idx) => {
          if (idx === 1) handleExportPdf();
          if (idx === 2) handleEdit();
        },
      );
    } else {
      setMenuVisible(true);
    }
  }, [handleExportPdf, handleEdit]);

  if (!cl) {
    return (
      <SafeAreaView
        style={[styles.safe, { backgroundColor: colors.background }]}
      >
        <View style={styles.notFound}>
          <Ionicons name="mail-outline" size={40} color={colors.textTertiary} />
          <Text style={[styles.notFoundText, { color: colors.textSecondary }]}>
            Cover letter not found
          </Text>
          <TouchableOpacity onPress={() => router.back()}>
            <Text style={[styles.backLink, { color: colors.accent }]}>
              Go back
            </Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={[styles.safe, { backgroundColor: colors.background }]}>
      {/* Top bar */}
      <View style={[styles.topBar, { borderBottomColor: colors.border }]}>
        <TouchableOpacity onPress={() => router.back()} style={styles.topBtn}>
          <Ionicons name="arrow-back" size={22} color={colors.text} />
        </TouchableOpacity>
        <Text
          style={[styles.topTitle, { color: colors.text }]}
          numberOfLines={1}
        >
          {cl.title ?? "Cover Letter"}
        </Text>
        <TouchableOpacity
          onPress={handleMorePress}
          disabled={exporting}
          style={styles.topBtn}
        >
          {exporting ? (
            <ActivityIndicator size="small" color={colors.accent} />
          ) : (
            <Ionicons
              name="ellipsis-horizontal"
              size={22}
              color={colors.text}
            />
          )}
        </TouchableOpacity>
      </View>

      <ActionMenu
        visible={menuVisible}
        onClose={() => setMenuVisible(false)}
        onExport={handleExportPdf}
        onEdit={handleEdit}
        colors={colors}
      />

      <ScrollView
        contentContainerStyle={styles.scroll}
        showsVerticalScrollIndicator={false}
      >
        {/* Meta card */}
        <View
          style={[
            styles.metaCard,
            { backgroundColor: colors.surface, borderColor: colors.border },
          ]}
        >
          <Text style={[styles.clTitle, { color: colors.text }]}>
            {cl.title ?? "Cover Letter"}
          </Text>

          {cl.tone ? (
            <View
              style={[
                styles.toneBadge,
                {
                  backgroundColor: colors.accent + "18",
                  borderColor: colors.accent + "35",
                },
              ]}
            >
              <Text style={[styles.toneText, { color: colors.accent }]}>
                {TONE_LABELS[cl.tone] ?? cl.tone}
              </Text>
            </View>
          ) : null}

          <View style={styles.metaList}>
            <MetaRow
              icon="person-outline"
              label="To"
              value={cl.hiringManager}
              colors={colors}
            />
            <MetaRow
              icon="business-outline"
              label="Company"
              value={cl.company ?? ""}
              colors={colors}
            />
            <MetaRow
              icon="briefcase-outline"
              label="Role"
              value={cl.jobTitle ?? ""}
              colors={colors}
            />
          </View>
        </View>

        {/* Divider */}
        <View style={styles.dividerRow}>
          <View
            style={[styles.dividerLine, { backgroundColor: colors.border }]}
          />
          <Text style={[styles.dividerLabel, { color: colors.textTertiary }]}>
            LETTER
          </Text>
          <View
            style={[styles.dividerLine, { backgroundColor: colors.border }]}
          />
        </View>

        {/* Letter body */}
        <View
          style={[
            styles.letterCard,
            { backgroundColor: colors.surface, borderColor: colors.border },
          ]}
        >
          {cl.hiringManager ? (
            <Text style={[styles.greeting, { color: colors.text }]}>
              Dear {cl.hiringManager},
            </Text>
          ) : null}
          <Text style={[styles.bodyText, { color: colors.text }]}>
            {cl.body?.trim() || "No content yet."}
          </Text>
          <View style={styles.signOff}>
            <Text style={[styles.signOffText, { color: colors.textSecondary }]}>
              Sincerely,
            </Text>
          </View>
        </View>

        {cl.uploadedFile ? (
          <View
            style={[
              styles.attachRow,
              { backgroundColor: colors.surface, borderColor: colors.border },
            ]}
          >
            <Ionicons
              name="document-attach-outline"
              size={18}
              color={colors.textSecondary}
            />
            <Text
              style={[styles.attachText, { color: colors.textSecondary }]}
              numberOfLines={1}
            >
              {cl.uploadedFile.name}
            </Text>
          </View>
        ) : null}

        <View style={{ height: 60 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1 },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  topBtn: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  topTitle: { flex: 1, textAlign: "center", fontSize: 16, fontWeight: "700" },
  scroll: { padding: 18 },
  metaCard: { borderRadius: 18, borderWidth: 1, padding: 18, marginBottom: 20 },
  clTitle: { fontSize: 20, fontWeight: "800", marginBottom: 10 },
  toneBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
    borderWidth: 1,
    marginBottom: 14,
  },
  toneText: { fontSize: 12, fontWeight: "600" },
  metaList: { gap: 10 },
  metaRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  metaLabel: { fontSize: 12, fontWeight: "600", width: 56 },
  metaValue: { fontSize: 14, flex: 1 },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 16,
  },
  dividerLine: { flex: 1, height: StyleSheet.hairlineWidth },
  dividerLabel: { fontSize: 11, fontWeight: "700", letterSpacing: 1.5 },
  letterCard: {
    borderRadius: 18,
    borderWidth: 1,
    padding: 20,
    marginBottom: 16,
  },
  greeting: { fontSize: 15, fontWeight: "600", marginBottom: 16 },
  bodyText: { fontSize: 15, lineHeight: 26 },
  signOff: { marginTop: 20 },
  signOffText: { fontSize: 14 },
  attachRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
  },
  attachText: { flex: 1, fontSize: 13 },
  notFound: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  notFoundText: { fontSize: 16 },
  backLink: { fontSize: 15, fontWeight: "600" },
  // Action menu (Android)
  overlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  menuCard: {
    margin: 16,
    borderRadius: 18,
    borderWidth: 1,
    overflow: "hidden",
    marginBottom: 40,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    padding: 18,
  },
  menuItemText: { fontSize: 16, fontWeight: "600" },
  menuDivider: { height: StyleSheet.hairlineWidth, marginHorizontal: 18 },
});
